image_util.cc: disable warning from gcc 5
addresses:
  ../../ui/gfx/image/image_util.cc:50:6: error: assuming signed overflow does
  not occur when assuming that (X - c) <= X is always true
  [-Werror=strict-overflow]
  bool VisibleMargins(const ImageSkia& image, int* leading, int* trailing) {
       ^

Signed-off-by: Max Krummenacher <max.oss.09@gmail.com>

Upstream-Status: Pending
See the discussion on the issue in Chromium upstream:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/3uwBwunIa7g