bignum.cc: disable warning from gcc 5
addresses:
  ../../third_party/WebKit/Source/wtf/dtoa/bignum.cc:105:10: error: assuming
  signed overflow does not occur when assuming that (X + c) < X is always
  false [-Werror=strict-overflow]
      void Bignum::AssignDecimalString(Vector<const char> value) {
           ^

Signed-off-by: Max Krummenacher <max.oss.09@gmail.com>

Upstream-Status: Pending
See the discussion on the issue in Chromium upstream:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/3uwBwunIa7g